import { CardWeight } from '@/types/card';

// 天（節氣）卡牌（24張）
export const skyCards: CardWeight[] = [
  {
    id: 'sky01',
    name: '立春',
    category: '天',
    energy: 3,
    impact: 4,
    direction: 1,
    temporal: 3,
    intensity: 'low',
    keywords: ['新生', '啟動', '潛力'],
    infoA: '冰雪融化，新能量在暗處啟動。',
    infoB: '「這件事還在初期，你願意花時間陪它慢慢長大嗎？」'
  },
  {
    id: 'sky02',
    name: '雨水',
    category: '天',
    energy: 4,
    impact: 5,
    direction: 1,
    temporal: 2,
    intensity: 'low',
    keywords: ['資源', '接納', '精算'],
    infoA: '資源像小雨般降臨，不多但剛好。',
    infoB: '「環境給你的資源，你有沒有好好接住、精打細算？」'
  },
  {
    id: 'sky03',
    name: '驚蟄',
    category: '天',
    energy: 6,
    impact: 7,
    direction: 1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['打破', '熱鬧', '行動'],
    infoA: '一聲雷響打破僵局，局勢變熱鬧。',
    infoB: '「大家都動起來了，你是被逼著走，還是自己想衝？」'
  },
  {
    id: 'sky04',
    name: '春分',
    category: '天',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['平衡', '完美', '狀態'],
    infoA: '晝夜平分，處於最完美的平衡。',
    infoB: '「現在這種各方平衡的狀態，讓你覺得舒服還是卡卡的？」'
  },
  {
    id: 'sky05',
    name: '清明',
    category: '天',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['清朗', '現形', '真相'],
    infoA: '天氣清朗，原本看不清的事物現形。',
    infoB: '「既然一切都攤開來了，你還打算繼續假裝看不見嗎？」'
  },
  {
    id: 'sky06',
    name: '穀雨',
    category: '天',
    energy: 5,
    impact: 6,
    direction: 1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['灌溉', '基礎', '紮實'],
    infoA: '最後灌溉期，適合把基礎做紮實。',
    infoB: '「如果不急著看成果，你現在最想加強哪項基本功？」'
  },
  {
    id: 'sky07',
    name: '立夏',
    category: '天',
    energy: 7,
    impact: 7,
    direction: 1,
    temporal: 2,
    intensity: 'high',
    keywords: ['擴張', '快長', '加速'],
    infoA: '萬物快長，人際與項目進入擴張。',
    infoB: '「事情變多變快了，你確定你的體力與心情跟得上嗎？」'
  },
  {
    id: 'sky08',
    name: '小滿',
    category: '天',
    energy: 6,
    impact: 6,
    direction: 1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['飽滿', '希望', '等待'],
    infoA: '稻穗快飽滿了，雖未收成但見希望。',
    infoB: '「已經有一點成績了，你會想趕快收割還是再等一下？」'
  },
  {
    id: 'sky09',
    name: '芒種',
    category: '天',
    energy: 8,
    impact: 8,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['忙碌', '播種', '收穫'],
    infoA: '最忙時刻，播種與收穫同時進行。',
    infoB: '「你現在這麼忙，是為了重要的事，還是只是在瞎忙？」'
  },
  {
    id: 'sky10',
    name: '夏至',
    category: '天',
    energy: 10,
    impact: 9,
    direction: 0,
    temporal: 2,
    intensity: 'extreme',
    keywords: ['高峰', '轉折', '退場'],
    infoA: '能量最高點，物極必反，需留後路。',
    infoB: '「現在是你最有影響力的時候，你有想過怎麼退場嗎？」'
  },
  {
    id: 'sky11',
    name: '小暑',
    category: '天',
    energy: 7,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['悶熱', '壓力', '煩躁'],
    infoA: '天氣悶熱，環境壓力大，心生煩躁。',
    infoB: '「這種煩人的壓力，是別人的問題還是你要求太高？」'
  },
  {
    id: 'sky12',
    name: '大暑',
    category: '天',
    energy: 9,
    impact: 9,
    direction: -1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['頂點', '爆發', '崩潰'],
    infoA: '壓力頂點，易爆發衝突或崩潰。',
    infoB: '「如果快爆炸了，你有沒有勇氣先離開現場躲一下？」'
  },
  {
    id: 'sky13',
    name: '立秋',
    category: '天',
    energy: 6,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['轉向', '退去', '收尾'],
    infoA: '風向變了，熱鬧退去，思考收尾。',
    infoB: '「熱度退了一點，現在冷靜想，這件事還值得嗎？」'
  },
  {
    id: 'sky14',
    name: '處暑',
    category: '天',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['殘留', '已定', '波折'],
    infoA: '暑氣殘留，大勢已定，僅餘波折。',
    infoB: '「大局已定，你能不能放下那些沒意義的擔心了？」'
  },
  {
    id: 'sky15',
    name: '白露',
    category: '天',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 1,
    intensity: 'medium',
    keywords: ['轉涼', '冷卻', '決定'],
    infoA: '天氣轉涼，想法冷卻，適合做決定。',
    infoB: '「拿掉那些衝動和夢想，剩下的現實你真的能接受嗎？」'
  },
  {
    id: 'sky16',
    name: '秋分',
    category: '天',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['得失', '盤點', '資源'],
    infoA: '得失各半，適合盤點手頭資源。',
    infoB: '「有得必有失，你得到的東西真的值得付出的代價嗎？」'
  },
  {
    id: 'sky17',
    name: '寒露',
    category: '天',
    energy: 4,
    impact: 5,
    direction: -1,
    temporal: 2,
    intensity: 'low',
    keywords: ['下降', '冷清', '溫暖'],
    infoA: '氣溫下降，環境冷清，需尋溫暖。',
    infoB: '「現在環境變冷了，你打算硬撐還是找個伴商量？」'
  },
  {
    id: 'sky18',
    name: '霜降',
    category: '天',
    energy: 6,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['終結', '斷離', '放手'],
    infoA: '關係或機會即將終結，該斷則斷。',
    infoB: '「如果註定結束，你是捨不得它，還是不甘心放手？」'
  },
  {
    id: 'sky19',
    name: '立冬',
    category: '天',
    energy: 4,
    impact: 5,
    direction: 0,
    temporal: 3,
    intensity: 'low',
    keywords: ['休息', '回歸', '內心'],
    infoA: '進入休息模式，適合回歸家庭內心。',
    infoB: '「如果暫時沒有舞台了，回歸私生活你會覺得空虛嗎？」'
  },
  {
    id: 'sky20',
    name: '小雪',
    category: '天',
    energy: 3,
    impact: 4,
    direction: 0,
    temporal: 2,
    intensity: 'low',
    keywords: ['減弱', '休息', '喘氣'],
    infoA: '外在動能減弱，要求變少，適合睡覺。',
    infoB: '「好不容易能喘口氣，你能不能先不管別人好好休息？」'
  },
  {
    id: 'sky21',
    name: '大雪',
    category: '天',
    energy: 4,
    impact: 5,
    direction: 0,
    temporal: 3,
    intensity: 'low',
    keywords: ['封閉', '積蓄', '準備'],
    infoA: '環境封閉期，不宜變動，適合積蓄。',
    infoB: '「現在雖然沒發揮空間，你有沒有在偷偷準備大招？」'
  },
  {
    id: 'sky22',
    name: '冬至',
    category: '天',
    energy: 5,
    impact: 8,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['黑暗', '轉捩', '希望'],
    infoA: '黑暗最長，也是光明回來的轉捩點。',
    infoB: '「現在可能是最難熬的時候，你有感覺到新希望嗎？」'
  },
  {
    id: 'sky23',
    name: '小寒',
    category: '天',
    energy: 6,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['考驗', '艱難', '毅力'],
    infoA: '考驗未結束，環境艱難，需毅力。',
    infoB: '「就差最後一哩路，你想找藉口放棄還是再撐一下？」'
  },
  {
    id: 'sky24',
    name: '大寒',
    category: '天',
    energy: 7,
    impact: 8,
    direction: -1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['極限', '考驗', '洗禮'],
    infoA: '最冷之時，也是春天的最後洗禮。',
    infoB: '「最糟的情況就在這了，若這都挺得過還有什麼好怕？」'
  }
];

// 地（空間）卡牌（12張）
export const earthCards: CardWeight[] = [
  {
    id: 'earth01',
    name: '孤峰',
    category: '地',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['孤立', '視野', '資源'],
    infoA: '視野極佳但資源稀缺，無人支援。',
    infoB: '「你站這麼高是為了看清方向，還是想享受沒人管？」'
  },
  {
    id: 'earth02',
    name: '深淵',
    category: '地',
    energy: 5,
    impact: 8,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['未知', '恐懼', '寶藏'],
    infoA: '下方是未知恐懼，也藏著珍貴寶藏。',
    infoB: '「你不敢跳是因為下面太黑，還是不相信能跳過去？」'
  },
  {
    id: 'earth03',
    name: '平原',
    category: '地',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['機會', '競爭', '焦點'],
    infoA: '機會多、競爭也多，容易失去焦點。',
    infoB: '「路這麼寬你卻不動，是因為選擇太多讓你迷失了嗎？」'
  },
  {
    id: 'earth04',
    name: '迷宮',
    category: '地',
    energy: 4,
    impact: 6,
    direction: -1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['牆壁', '打轉', '出口'],
    infoA: '牆壁林立，雖安全但都在原地打轉。',
    infoB: '「你忙著找出口，但有沒有想過這牆是你自己蓋的？」'
  },
  {
    id: 'earth05',
    name: '要塞',
    category: '地',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 3,
    intensity: 'medium',
    keywords: ['防禦', '安全', '限制'],
    infoA: '防禦森嚴，提供安全感但也限制自由。',
    infoB: '「這牆保護你也關住你，你打算一輩子躲在裡面嗎？」'
  },
  {
    id: 'earth06',
    name: '孤島',
    category: '地',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['隔絕', '自給', '本事'],
    infoA: '被隔絕，須自給自足，無法賴外援。',
    infoB: '「現在沒人幫得了你，這是不是看清你本事的好機會？」'
  },
  {
    id: 'earth07',
    name: '十字路口',
    category: '地',
    energy: 5,
    impact: 8,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['抉擇', '停滯', '方向'],
    infoA: '動能停滯，必須做出方向性的抉擇。',
    infoB: '「撇開正確答案不談，哪條路走起來最讓你興奮？」'
  },
  {
    id: 'earth08',
    name: '溫室',
    category: '地',
    energy: 4,
    impact: 5,
    direction: 0,
    temporal: 3,
    intensity: 'low',
    keywords: ['舒適', '保護', '成長'],
    infoA: '環境舒適，有人遮風避雨，難長大。',
    infoB: '「若一直不出去淋雨，你還會記得怎麼戰鬥嗎？」'
  },
  {
    id: 'earth09',
    name: '獨木橋',
    category: '地',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['一人', '無退路', '平衡'],
    infoA: '只能一人通行，無退路，考驗平衡。',
    infoB: '「這路無法帶人走，你準備好要為了目標獨自前進嗎？」'
  },
  {
    id: 'earth10',
    name: '廢墟',
    category: '地',
    energy: 5,
    impact: 8,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['垮了', '荒涼', '重生'],
    infoA: '舊體系垮了，荒涼中藏著重生契機。',
    infoB: '「既然舊的已爛掉，你要花力氣修它還是乾脆蓋新的？」'
  },
  {
    id: 'earth11',
    name: '劇場',
    category: '地',
    energy: 7,
    impact: 7,
    direction: 1,
    temporal: 1,
    intensity: 'high',
    keywords: ['矚目', '表現', '演技'],
    infoA: '眾人矚目，需展現表現力與演技。',
    infoB: '「現在大家都在看，你是演給人看，還是演自己愛的？」'
  },
  {
    id: 'earth12',
    name: '後花園',
    category: '地',
    energy: 3,
    impact: 4,
    direction: 1,
    temporal: 3,
    intensity: 'low',
    keywords: ['私密', '放鬆', '休養'],
    infoA: '私密放鬆空間，無競爭，適合休養。',
    infoB: '「不用交成績單的時候，你最想把時間花在什麼事上？」'
  }
];

// 人（角色）卡牌（18張）
export const humanCards: CardWeight[] = [
  {
    id: 'human01',
    name: '繼承者',
    category: '人',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 3,
    intensity: 'high',
    keywords: ['巨人', '承接', '決定'],
    infoA: '你正站在巨人的肩膀上，承接他人的資源、名聲或遺留的問題。',
    infoB: '「你現在做的這些決定，是為了讓前輩滿意，還是為了你自己？」'
  },
  {
    id: 'human02',
    name: '局外人',
    category: '人',
    energy: 4,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['距離', '觀察', '格格不入'],
    infoA: '你與核心圈保持距離，能客觀觀察，但也感到格格不入。',
    infoB: '「你是真的不屑加入他們，還是因為害怕被拒絕，所以先假裝不需要？」'
  },
  {
    id: 'human03',
    name: '調停者',
    category: '人',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['衝突', '主持', '委屈'],
    infoA: '你處在衝突的中心，大家都希望你出來主持公道或緩和氣氛。',
    infoB: '「你在忙著讓每個人都滿意的時候，是不是把自己內心的委屈給藏起來了？」'
  },
  {
    id: 'human04',
    name: '領航員',
    category: '人',
    energy: 8,
    impact: 9,
    direction: 1,
    temporal: 2,
    intensity: 'high',
    keywords: ['領導', '責任', '指引'],
    infoA: '眾人的目光都在你身上，等待你下達指令，你是團隊的風向球。',
    infoB: '「如果你其實也不知道路在哪裡，你有勇氣跟你的團隊坦白這件事嗎？」'
  },
  {
    id: 'human05',
    name: '隱士',
    category: '人',
    energy: 4,
    impact: 6,
    direction: 0,
    temporal: 3,
    intensity: 'medium',
    keywords: ['獨處', '思考', '隔離'],
    infoA: '你主動切斷了社交連結，選擇獨自思考，外界很難影響你。',
    infoB: '「你現在的沉默是為了尋找答案，還是只是想逃避那些讓你頭痛的人？」'
  },
  {
    id: 'human06',
    name: '競爭者',
    category: '人',
    energy: 7,
    impact: 8,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['對抗', '威脅', '證明'],
    infoA: '你處於高度對抗的環境，身邊的人既是夥伴，也是威脅。',
    infoB: '「如果沒有這個對手來刺激你，你還會這麼努力地證明自己的價值嗎？」'
  },
  {
    id: 'human07',
    name: '後援者',
    category: '人',
    energy: 5,
    impact: 6,
    direction: 1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['隱藏', '支撐', '看見'],
    infoA: '你的光芒隱藏在他人背後，默默支撐著計畫，不求名分。',
    infoB: '「你是真的享受這種『成功不必在我』的感覺，還是你其實也渴望被看見？」'
  },
  {
    id: 'human08',
    name: '反叛者',
    category: '人',
    energy: 7,
    impact: 8,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['挑戰', '懷疑', '戰鬥'],
    infoA: '你正在挑戰既有的規則或權威，周遭充滿懷疑與不認同。',
    infoB: '「你是在為了正確的價值觀戰鬥，還是只是單純地想要反對這一切？」'
  },
  {
    id: 'human09',
    name: '崇拜者',
    category: '人',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 2,
    intensity: 'medium',
    keywords: ['模仿', '神格', '自卑'],
    infoA: '你眼裡只有某個強大的對象，試圖模仿他，甚至將他神格化。',
    infoB: '「你這麼崇拜他，是因為他真的很棒，還是因為你想透過他來補足自卑？」'
  },
  {
    id: 'human10',
    name: '導師',
    category: '人',
    energy: 7,
    impact: 7,
    direction: 1,
    temporal: 2,
    intensity: 'high',
    keywords: ['傳授', '照顧', '價值'],
    infoA: '你正在傳授經驗，照顧比你資淺的人，感受被需要的價值。',
    infoB: '「你在教別人的時候，是在分享智慧，還是只是想享受那種『高人一等』的感覺？」'
  },
  {
    id: 'human11',
    name: '流浪者',
    category: '人',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 1,
    intensity: 'medium',
    keywords: ['不穩定', '離開', '承諾'],
    infoA: '你的關係並不穩定，隨時準備離開，不對任何一段關係承諾。',
    infoB: '「你這麼急著想走，是因為這裡真的沒留戀了，還是你害怕一旦安定就會受傷？」'
  },
  {
    id: 'human12',
    name: '救贖者',
    category: '人',
    energy: 6,
    impact: 7,
    direction: 1,
    temporal: 2,
    intensity: 'high',
    keywords: ['解決', '苦海', '救贖'],
    infoA: '你習慣性地想去解決別人的問題，想把每個人都帶出苦海。',
    infoB: '「你這麼想救別人，是不是因為你心裡也有一個地方正等著被救贖？」'
  },
  {
    id: 'human13',
    name: '旁觀者',
    category: '人',
    energy: 4,
    impact: 5,
    direction: 0,
    temporal: 2,
    intensity: 'low',
    keywords: ['保護', '冷血', '看著'],
    infoA: '你在岸上看著別人溺水或狂歡，不插手、不評價，僅僅看著。',
    infoB: '「你把自己保護得這麼好，但也變成了關係裡的冷血動物，這是你要的嗎？」'
  },
  {
    id: 'human14',
    name: '背叛者',
    category: '人',
    energy: 6,
    impact: 8,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['轉向', '離開', '利益'],
    infoA: '你正處於轉向的邊緣，可能為了更高的利益或生存而選擇離開。',
    infoB: '「如果離開這段關係會讓你被罵，你還能理直氣壯地說這是為了自己好嗎？」'
  },
  {
    id: 'human15',
    name: '學徒',
    category: '人',
    energy: 5,
    impact: 6,
    direction: 1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['學習', '犯錯', '謙卑'],
    infoA: '你正放下身段向環境學習，容許自己犯錯，也接受別人的指點。',
    infoB: '「你現在這種『我不懂』的狀態，是真心的謙卑，還是逃避責任的藉口？」'
  },
  {
    id: 'human16',
    name: '玩伴',
    category: '人',
    energy: 4,
    impact: 5,
    direction: 1,
    temporal: 1,
    intensity: 'low',
    keywords: ['享樂', '當下', '責任'],
    infoA: '你們的關係建立在享樂與當下，不談未來，也不承擔沈重責任。',
    infoB: '「如果撇開這些玩樂，你們坐下來安靜地聊天，你還會想跟這個人在一起嗎？」'
  },
  {
    id: 'human17',
    name: '守門人',
    category: '人',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['權力', '決定', '重要'],
    infoA: '你掌握著某種權力或資訊，由你決定誰能進場，誰必須離開。',
    infoB: '「你現在握著這個權力，你是想幫大家解決問題，還是想證明你很重要？」'
  },
  {
    id: 'human18',
    name: '陌生人',
    category: '人',
    energy: 4,
    impact: 6,
    direction: -1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['孤寂', '無法交會', '走遠'],
    infoA: '你在人群中感到孤寂，雖然身邊有人，但靈魂無法交會。',
    infoB: '「如果你現在對身邊的人感到陌生，是因為他們變了，還是你已經走太遠了？」'
  }
];

// 變數（意外）卡牌（18張）
export const variableCards: CardWeight[] = [
  {
    id: 'var01',
    name: '閃電',
    category: '變數',
    energy: 9,
    impact: 10,
    direction: -1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['打擊', '摧毀', '核心'],
    infoA: '突如其來的打擊，瞬間摧毀了你原本引以為傲的某個部分。',
    infoB: '「當最慘的事發生時，你第一個想保護的是什麼？那才是你真正的核心。」'
  },
  {
    id: 'var02',
    name: '地震',
    category: '變數',
    energy: 8,
    impact: 9,
    direction: -1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['動搖', '裂痕', '重新'],
    infoA: '根基動搖，你原本認為很穩定的事（如工作、感情）出現裂痕。',
    infoB: '「如果現在的安穩都是假象，你敢不敢推倒一切重新來過？」'
  },
  {
    id: 'var03',
    name: '彩虹',
    category: '變數',
    energy: 6,
    impact: 5,
    direction: 1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['誘惑', '機會', '分心'],
    infoA: '出現一個美麗但短暫的誘惑，看起來像機會，但也可能是分心。',
    infoB: '「這好事發生得太突然了，你是在慶幸好運，還是懷疑這只是個陷阱？」'
  },
  {
    id: 'var04',
    name: '迷路',
    category: '變數',
    energy: 5,
    impact: 6,
    direction: 0,
    temporal: 1,
    intensity: 'medium',
    keywords: ['失效', '陌生', '直覺'],
    infoA: '導航失效，你發現原本走的路通往一個完全陌生的地方。',
    infoB: '「在沒人告訴你方向的時候，你敢不敢相信自己的直覺走一次？」'
  },
  {
    id: 'var05',
    name: '止步',
    category: '變數',
    energy: 4,
    impact: 6,
    direction: -1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['關上', '無法前進', '轉身'],
    infoA: '門被關上了，某種外在力量強制讓你無法再前進。',
    infoB: '「如果這條路注定走不通，你能不能轉過身，看看身後被你忽略的風景？」'
  },
  {
    id: 'var06',
    name: '加速',
    category: '變數',
    energy: 7,
    impact: 7,
    direction: 0,
    temporal: 1,
    intensity: 'high',
    keywords: ['快', '無法掌控', '煞車'],
    infoA: '事情進展快到你無法掌控，你被局勢推著往前衝。',
    infoB: '「當一切都快得讓你喘不過氣時，你敢不敢主動踩下煞車？」'
  },
  {
    id: 'var07',
    name: '空白',
    category: '變數',
    energy: 3,
    impact: 5,
    direction: 0,
    temporal: 2,
    intensity: 'low',
    keywords: ['消失', '寂靜', '存在'],
    infoA: '訊號全無，所有人都消失了，你進入一段極度的寂靜期。',
    infoB: '「在沒有人給你反饋、沒有訊息進來時，你還能感受到自己的存在嗎？」'
  },
  {
    id: 'var08',
    name: '禮物',
    category: '變數',
    energy: 6,
    impact: 6,
    direction: 1,
    temporal: 1,
    intensity: 'medium',
    keywords: ['支援', '代價', '交換'],
    infoA: '得到一份你沒預料到的支援，但這份禮物可能帶著隱形的代價。',
    infoB: '「這份好處拿得你心安理得嗎？你準備好要拿什麼去交換它了嗎？」'
  },
  {
    id: 'var09',
    name: '醜聞',
    category: '變數',
    energy: 7,
    impact: 8,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['揭開', '真相', '解脫'],
    infoA: '隱藏的秘密被揭開，某種真相曝光，引發了公眾或周遭的討論。',
    infoB: '「如果你最想隱瞞的事被知道了，你覺得那是毀滅，還是徹底的解脫？」'
  },
  {
    id: 'var10',
    name: '遺失',
    category: '變數',
    energy: 6,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['弄丟', '重要', '失去'],
    infoA: '你弄丟了某個對你很重要、且無法取代的東西。',
    infoB: '「你現在這麼痛苦，是因為那個東西真的很重要，還是你只是不習慣失去？」'
  },
  {
    id: 'var11',
    name: '相遇',
    category: '變數',
    energy: 6,
    impact: 7,
    direction: 1,
    temporal: 2,
    intensity: 'high',
    keywords: ['遇到', '改變', '冒險'],
    infoA: '遇到一個完全不在計畫中的人，徹底改變了你的思考邏輯。',
    infoB: '「這個人的出現打亂了你的秩序，你是想把他推開，還是想跟他一起冒險？」'
  },
  {
    id: 'var12',
    name: '重逢',
    category: '變數',
    energy: 6,
    impact: 7,
    direction: 0,
    temporal: 2,
    intensity: 'high',
    keywords: ['陰影', '舊人', '了結'],
    infoA: '過去的陰影或舊人重新出現，要求你再次面對未竟之志。',
    infoB: '「這次你打算用跟當年一樣的方法逃避，還是要勇敢地做個了結？」'
  },
  {
    id: 'var13',
    name: '崩塌',
    category: '變數',
    energy: 8,
    impact: 9,
    direction: -1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['瓦解', '失誤', '重新開始'],
    infoA: '你辛苦建立的某個系統或計畫，因為一個小細節的失誤而瓦解。',
    infoB: '「如果這件事必須從零開始，你心裡湧上的是絕望，還是重新開始的興奮？」'
  },
  {
    id: 'var14',
    name: '狂風',
    category: '變數',
    energy: 7,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['嘈雜', '謠言', '心跳'],
    infoA: '環境變得非常嘈雜，謠言四起，讓你很難聽到自己內心的聲音。',
    infoB: '「在這麼亂的時候，你能不能閉上眼睛，只聽你自己的心跳聲？」'
  },
  {
    id: 'var15',
    name: '乾涸',
    category: '變數',
    energy: 4,
    impact: 6,
    direction: -1,
    temporal: 2,
    intensity: 'medium',
    keywords: ['耗盡', '空', '枯萎'],
    infoA: '靈感或資源突然耗盡，你感到自己空空的，擠不出任何東西。',
    infoB: '「既然已經空了，你為什麼不乾脆停下來，讓自己徹底枯萎一陣子？」'
  },
  {
    id: 'var16',
    name: '火花',
    category: '變數',
    energy: 6,
    impact: 8,
    direction: 1,
    temporal: 1,
    intensity: 'high',
    keywords: ['靈感', '點燃', '燒掉'],
    infoA: '一個微小的靈感閃過，雖然微弱，但足以點燃整片森林。',
    infoB: '「這個小小的念頭讓你心跳加速了嗎？你願意為了它燒掉現在的安穩嗎？」'
  },
  {
    id: 'var17',
    name: '陷阱',
    category: '變數',
    energy: 6,
    impact: 7,
    direction: -1,
    temporal: 1,
    intensity: 'high',
    keywords: ['圈套', '抱怨', '爬出來'],
    infoA: '你發現自己掉進了一個設計好的圈套，或是自己挖的坑。',
    infoB: '「你現在忙著抱怨別人害你，還是忙著思考怎麼從這個坑裡爬出來？」'
  },
  {
    id: 'var18',
    name: '奇蹟',
    category: '變數',
    energy: 10,
    impact: 10,
    direction: 1,
    temporal: 1,
    intensity: 'extreme',
    keywords: ['轉機', '不合理', '警告'],
    infoA: '必死之局突然出現轉機，一個完全不合理的解法生效了。',
    infoB: '「當奇蹟發生的時候，你是覺得自己應得的，還是覺得這是一次警告？」'
  }
];

// 所有卡牌
export const allCards: CardWeight[] = [
  ...skyCards,
  ...earthCards,
  ...humanCards,
  ...variableCards
];

// 根據類別獲取卡牌
export function getCardsByCategory(category: CardWeight['category']): CardWeight[] {
  return allCards.filter(card => card.category === category);
}

// 根據ID獲取卡牌
export function getCardById(id: string): CardWeight | undefined {
  return allCards.find(card => card.id === id);
}

// 隨機抽取一張卡牌
export function drawRandomCard(category?: CardWeight['category']): CardWeight {
  const cards = category ? getCardsByCategory(category) : allCards;
  const randomIndex = Math.floor(Math.random() * cards.length);
  return cards[randomIndex];
}

